// src/component/PrimitiveValueInput/PrimitiveValueInput.tsx
import { EnumTypeDefinition, PrimitiveTypeDefinition } from "@tws-js/common"
import FloatInput from "../FloatInput/FloatInput"
import SecretInput from "../SecretInput/SecretInput"
import StringInput from "../StringInput/StringInput"
import IntInput from "../IntInput/IntInput"
import BooleanInput from "../BooleanInput/BooleanInput"
import { Value, StringValue, NumberValue, BooleanValue } from "../../utils"
import Select from "../Select/Select"

function PrimitiveValueInput(props: {
  definition: PrimitiveTypeDefinition | EnumTypeDefinition;
  initialValue: Value;
  onChange: (value: Value) => void;
  isSecret: boolean;
}) {
  const { isSecret, definition, initialValue, onChange } = props;

  return (
    <div className="primitive-value-input-root">
      {definition.type === 'string' && (
        isSecret ? <SecretInput
              placeholder={definition.defaultValue !== undefined ? String(definition.defaultValue) : undefined}
              initialValue={StringValue.from(initialValue)}
              onChange={(value) => onChange(value)}
              required={definition.required !== false}
            />
          : <StringInput
              placeholder={definition.defaultValue !== undefined ? String(definition.defaultValue) : undefined}
              initialValue={StringValue.from(initialValue)}
              onChange={(value) => onChange(value)}
              multiline={true}
              required={definition.required !== false}
            />
      )}

      {definition.type === 'int' && (
        <IntInput
          placeholder={definition.defaultValue !== undefined ? String(definition.defaultValue) : undefined}
          initialValue={NumberValue.from(initialValue)}
          onChange={(value) => onChange(value)}
          required={definition.required !== false}
        />
      )}

      {definition.type === 'float' && (
        <FloatInput
          placeholder={definition.defaultValue !== undefined ? String(definition.defaultValue) : undefined}
          initialValue={NumberValue.from(initialValue)}
          onChange={(value) => onChange(value)}
          required={definition.required !== false}
        />
      )}

      {definition.type === 'boolean' && (
        <BooleanInput
          initialValue={(
            initialValue.isNull() ? BooleanValue.from(definition.defaultValue) : BooleanValue.from(initialValue)
          )}
          onChange={(value) => onChange(value)}
        />
      )}

      {definition.type === 'enum' && (
        <Select
          options={Object.entries(definition.values).map(([enumKey, enumItem]) => ({
            label: enumItem.title || enumKey,
            value: enumKey,
          }))}
          initialValue={StringValue.from(initialValue)}
          onChange={(value) => onChange(value)}
          required={definition.required !== false}
        />
      )}
    </div>
  );
}

export default PrimitiveValueInput;

// src/form/PrimitiveValueInput.svelte
<script lang="ts">
import { createEventDispatcher } from 'svelte';
import type { PrimitiveTypeDefinition } from '@tws-js/common';

import BooleanInput from '../component/BooleanInput.svelte';
import IntInput from '../component/IntInput.svelte';
import FloatInput from '../component/FloatInput.svelte';
import StringInput from '../component/StringInput.svelte';
import NamedInput from './NamedInput.svelte';
import SecretInput from '../component/SecretInput.svelte';

export let key: string | undefined = undefined;
export let removable: boolean;
export let definition: PrimitiveTypeDefinition;

const typeIsKnown = (
  ['string', 'int', 'float', 'boolean', 'object'].includes(definition.type)
);

const dispatch = createEventDispatcher();

function onChange(value: unknown) {
  dispatch('change', { value });
}

export let value: unknown;
</script>

<NamedInput
  name={definition.title || key}
  description={definition.description}
  required={definition.required !== false}
  {removable}
  on:remove
>
  {#if definition.type === 'string'}
    {#if key && key.toLowerCase().includes('password')}
      <SecretInput
        placeholder={definition.defaultValue !== undefined ? String(definition.defaultValue) : undefined}
        value={typeof value === 'string' ? value : undefined}
        on:change={(event) => {
          value = event.detail.value;
          onChange(value);
        }}
      />
    {:else}
      <StringInput
        placeholder={definition.defaultValue !== undefined ? String(definition.defaultValue) : undefined}
        value={typeof value === 'string' ? value : undefined}
        on:change={(event) => {
          value = event.detail.value;
          onChange(value);
        }}
      />
    {/if}
  {/if}

  {#if definition.type === 'int'}
    <IntInput
      placeholder={definition.defaultValue !== undefined ? String(definition.defaultValue) : undefined}
      value={typeof value === 'number' ? value : undefined}
      on:change={(event) => {
        value = event.detail.value;
        onChange(value);
      }}
    />
  {/if}

  {#if definition.type === 'float'}
    <FloatInput
      placeholder={definition.defaultValue !== undefined ? String(definition.defaultValue) : undefined}
      value={typeof value === 'number' ? value : undefined}
      on:change={(event) => {
        value = event.detail.value;
        onChange(value);
      }}
    />
  {/if}

  {#if definition.type === 'boolean'}
    <BooleanInput
      value={typeof definition.defaultValue === 'boolean' ? definition.defaultValue : undefined}
      on:change={(event) => {
        value = event.detail.value;
        onChange(value);
      }}
    />
  {/if}
</NamedInput>

{#if !typeIsKnown}
  <div>
    <div>Unknown type</div>
    <pre>{JSON.stringify(definition, null, 2)}</pre>
  </div>
{/if}
