// src/view/Input.svelte
<script lang="ts">
import { createEventDispatcher } from 'svelte';
import type {
  ArrayTypeDefinition, EnumTypeDefinition, ObjectTypeDefinition, PrimitiveTypeDefinition,
} from '@tws-js/common';

import ArrayInput from '../form/ArrayInput.svelte';
import PrimitiveValueInput from '../form/PrimitiveValueInput.svelte';
import ObjectInput from '../form/ObjectInput.svelte';
import { getArrayFromRecord, getObjectFromRecord } from '../utils';
import EnumInput from '../form/EnumInput.svelte';

export let key: string;

export let definition:
  | PrimitiveTypeDefinition
  | ObjectTypeDefinition
  | ArrayTypeDefinition
  | EnumTypeDefinition;

const typeIsKnown = (
  definition.type === 'array'
  && ['string', 'int', 'float', 'boolean', 'object'].includes(definition.item.type)
) || (
  definition.type !== 'array'
  && ['string', 'int', 'float', 'boolean', 'object', 'enum'].includes(definition.type)
);

let input: Record<string, unknown> = {};

const dispatch = createEventDispatcher();

function onChange() {
  input = input;
  dispatch('change', { value: input[key] });
}
</script>

{#if definition.type !== 'array' && definition.type !== 'object' && definition.type !== 'enum'}
  <PrimitiveValueInput
    key={key}
    definition={definition}
    value={input[key]}
    on:change={(event) => {
      input[key] = event.detail.value;
      onChange();
    }}
    removable={definition.required === false}
    on:remove={() => {
      delete input[key];
      onChange();
    }}
  />
{/if}

{#if definition.type === 'array'}
  <ArrayInput
    key={key}
    definition={definition}
    value={getArrayFromRecord(input, key)}
    on:change={(event) => {
      input[key] = event.detail.value;
      onChange();
    }}
    removable={false}
  />
{/if}

{#if definition.type === 'object'}
  <ObjectInput
    key={key}
    definition={definition}
    value={getObjectFromRecord(input, key)}
    on:change={(event) => {
      input[key] = event.detail.value;
      onChange();
    }}
    removable={definition.required === false}
    on:remove={() => {
      delete input[key];
      onChange();
    }}
  />
{/if}

{#if definition.type === 'enum'}
  <EnumInput
    key={key}
    definition={definition}
    value={input[key]}
    on:change={(event) => {
      input[key] = event.detail.value;
      onChange();
    }}
    removable={definition.required === false}
    on:remove={() => {
      delete input[key];
      onChange();
    }}
  />
{/if}

{#if !typeIsKnown}
  <div>
    <div>Unknown type</div>
    <pre>{JSON.stringify(definition, null, 2)}</pre>
  </div>
{/if}

// src/component/Input/Input.tsx
import {
  ArrayTypeDefinition, EnumTypeDefinition, ObjectTypeDefinition, PrimitiveTypeDefinition,
} from "@tws-js/common";
import ArrayInput from "../ArrayInput/ArrayInput";
import PrimitiveValueInput from "../PrimitiveValueInput/PrimitiveValueInput";
import { ArrayValue, clearAllSelections, newValueFromType, ObjectValue, Value } from "../../utils";
import ObjectInput from "../ObjectInput/ObjectInput";
import UnknownType from "../UnknownType/UnknownType";
import Info from "../Info/Info";
import { useRef } from "react";

import './Input.css';

function Input(props: {
  attributeName: string
  definition:
    | PrimitiveTypeDefinition
    | ObjectTypeDefinition
    | ArrayTypeDefinition
    | EnumTypeDefinition
  initialValue: Value
  onChange: (value: Value) => void
  showName: boolean
}) {
  const { attributeName, definition, initialValue, onChange, showName } = props;

  const typeIsKnown = (
    definition.type === 'array'
    && ['string', 'int', 'float', 'boolean', 'object', 'enum'].includes(definition.item.type)
  ) || (
    definition.type !== 'array'
    && ['string', 'int', 'float', 'boolean', 'object', 'enum'].includes(definition.type)
  );

  const childrenRef = useRef<HTMLDivElement>(null);

  const name = (definition.title || attributeName).trim().replace(/:+$/, '');

  return (
    <div className={`input-root ${definition.type === 'boolean' ? 'input-boolean' : ''}`}>
      <div onClick={() => {
        if (definition.type === 'boolean') {
          clearAllSelections();
        }

        const firstFocusableInput = childrenRef
          .current?.querySelector('input, textarea, select') as
          HTMLElement | null;
        if (firstFocusableInput) {
          firstFocusableInput.focus();
          firstFocusableInput.click();
        }
      }}>
        {definition.type !== 'array' && definition.required === false && (
          <span className="input-optional">(Optional)</span>
        )}
        {showName && name && (
          <span className="input-name">{
            name.endsWith('?') ? name : (
              definition.type === 'boolean' ? name : `${name}:`
            )
          }</span>
        )}
        {definition.description && <Info text={definition.description} />}
      </div>
      <div ref={childrenRef}>
        {typeIsKnown && definition.type !== 'array' && definition.type !== 'object' && (
          <PrimitiveValueInput
            definition={definition}
            initialValue={newValueFromType(definition.type, initialValue.value)}
            onChange={onChange}
            isSecret={attributeName.toLowerCase().includes('password')
              || attributeName.toLowerCase().includes('secret')
              || attributeName.toLowerCase().includes('token')}
          />
        )}

        {definition.type === 'array' && (
          <ArrayInput
            attributeName={attributeName}
            definition={definition}
            initialValue={ArrayValue.from(initialValue)}
            onChange={onChange}
          />
        )}

        {definition.type === 'object' && (
        <ObjectInput
          definition={definition}
          initialValue={ObjectValue.from(initialValue)}
          onChange={onChange}
        />
        )}

        {!typeIsKnown && (
          <UnknownType definition={JSON.stringify(definition, null, 2)} />
        )}
      </div>
    </div>
  )
}

export default Input;
